### ISSUE TITLE
Separate package for FileSystemStore

### ISSUE THREAD

**Issue by keller-mark** [manzt/zarrita.js#205]
The `node:` dependencies in `FileSystemStore` complicate usage of `@zarrita/storage`.

Even if only non-node stores like `ReferenceStore` are imported using syntax like

```js
import { ReferenceStore } from '@zarrita/storage';
```

bundlers are not smart enough.

Minimal example: https://stackblitz.com/edit/vitejs-vite-afkkaz?file=src%2Fmain.ts&file=package.json (run `npm run build` in terminal)

<img width="1497" alt="Screenshot 2024-08-23 at 10 58 27 AM" src="https://github.com/user-attachments/assets/82a63535-6afc-4d62-8099-b18eb9f52798">

## Possible solutions

Can FileSystemStore live in its own sub-pacakge? Or can all other stores be imported into a new sub-package like `@zarrita/storage-browser` (which would be non-breaking)?

**Comment by keller-mark** [comment]
I am currently using `pnpm patch` to remove this line, which is another option

https://github.com/manzt/zarrita.js/blob/c7167cb2d16a62786cd5d734615a52acb6652791/packages/storage/src/index.ts#L2C21-L2C36

**Comment by manzt** [comment]
Would you be able to do:

```javascript
import ReferenceStore from "@zarrita/storage/ref";
```

?

**Comment by manzt** [comment]
I've tried to code-split each store as a separate package entrypoint for this reason, but I'm starting to think it would be easier to implement as separately versioned packages.

**Comment by manzt** [comment]
Ooo thanks for trying, would you be able to try `nodenext`? Just curious...

**Comment by keller-mark** [comment]
I tried `nodenext`, but then it tells me I also need to change my `module` value. I am not sure the optimal tsconfig and what downstream effects changing these properties will have

**Comment by keller-mark** [comment]
For reference, this is the current file: https://github.com/vitessce/vitessce/blob/main/tsconfig.json

**Comment by manzt** [comment]
Got it. I was hoping the entrypoints would work but maybe it's a bit too restrictive and we should just have separate packages.

**Comment by keller-mark** [comment]
`"moduleResolution": "Bundler"` seems to be working, so maybe that is the best / most modern solution, and can just be documented in the docs site somewhere

**Comment by keller-mark** [comment]
Changing the import statement to use the entry point in the minimal reproducer linked above also resolves the issue so please feel free to close this issue

**Comment by manzt** [comment]
Ok, I'll close for now but feel free to reopen if you find that doesn't work for a future use case!
