### ISSUE TITLE
Option to Specify Zarr v3

### ISSUE THREAD

**Issue by will-moore** [manzt/zarrita.js#216]
I'm wondering if it's possible to tell Zarrita that I know the zarr is v3, instead of letting it figure this out itself?

I imagine that mostly it's a pretty insignificant cost to test for `.zattrs` or `.zarray` and then if they are 404 then try `zarr.json`,
but in my case I'm trying to load a lot of zarr images as thumbnails on a page, as fast as possible:

Work in progress at https://ome.github.io/ome2024-ngff-challenge/

As you can see, there are a ton of 404s and I feel that the thumbnails might be a bit quicker if I could specify to try Zarr v3 directly?
 Cheers!

**Comment by manzt** [comment]
It's already possible! see https://zarrita.dev/cookbook.html#open-array-or-group-with-strict-version

**Comment by will-moore** [comment]
Great - Thanks (sorry I didn't get that far in the docs)
