### ISSUE TITLE
zarr.get() abort

### ISSUE THREAD

**Issue by will-moore** [manzt/zarrita.js#218]
Hi,

I see that you can pass a signal into e.g.

```
await store.get("/zarr.json", {
	headers: { foo: "bar" },
	signal: controller.signal,
});
```
But can you do the same when I'm loading slices, or is there another way I could abort these requests when components are destroyed?
I tried:
```
zarr.get(arr, slices, {signal: controller.signal});
```

But it complains: "Object literal may only specify known properties, and 'signal' does not exist in type 'GetOptions<RequestInit>'"

Thanks!

**Comment by manzt** [comment]
> But it complain

"it" here is a TypeScript error, correct?

The options bag for `zarr.get` has an `opts` key which is forwarded down to the underlying store. There are more than just store options when slices need to be stitched together.

https://github.com/manzt/zarrita.js/blob/929c8a0d4f7e29eba6bef6aa6fec7361015438b5/packages/indexing/src/types.ts#L47

we could consider renaming `storeOptions` to be more explicit.

```javascript
import * as zarr from "npm:zarrita@next";

const store = new zarr.FetchStore("");
const arr = await zarr.open(store, { kind: "array" });

const controller = new AbortController();
zarr.get(arr, [null, 0], { opts: { signal: controller.signal } });
```
